[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.web-secure]
    address = ":443"

[api]
  insecure = true

[acme]
  storage = "/etc/traefik/acme/acme.json"

[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  exposedByDefault = false
